# -*- coding: utf-8 -*-
"""
Automated Nginx Security Hardener & VHost Config Generator
Author: Eng. MHD. Shadi AL-Hasan <mhd.shadi.alhasan@gmail.com>
Phone: +963934005922
Copyright (c) 2026 MHD. Shadi AL-Hasan
"""

import os
import argparse
from pathlib import Path
from typing import Tuple, List, Dict

# Rate Limiting Presets for Nginx
RATE_LIMIT_PRESETS: Dict[str, Dict[str, str]] = {
    "strict": {
        "rate": "10r/s",
        "burst": "20",
        "zone_size": "10m",
        "description": "High security: 10 req/sec with burst of 20, instant drop."
    },
    "standard": {
        "rate": "30r/s",
        "burst": "50",
        "zone_size": "10m",
        "description": "Balanced production: 30 req/sec with burst of 50."
    },
    "relaxed": {
        "rate": "100r/s",
        "burst": "150",
        "zone_size": "20m",
        "description": "High traffic: 100 req/sec with burst of 150."
    },
    "off": {
        "rate": "",
        "burst": "",
        "zone_size": "",
        "description": "Rate limiting disabled."
    }
}

# Production Security Header Presets
SECURITY_HEADER_PRESETS: Dict[str, List[str]] = {
    "strict": [
        'add_header X-Frame-Options "DENY" always;',
        'add_header X-XSS-Protection "1; mode=block" always;',
        'add_header X-Content-Type-Options "nosniff" always;',
        'add_header Referrer-Policy "strict-origin-when-cross-origin" always;',
        'add_header Permissions-Policy "geolocation=(), camera=(), microphone=(), payment=()" always;',
        'add_header Cross-Origin-Embedder-Policy "require-corp" always;',
        'add_header Cross-Origin-Opener-Policy "same-origin" always;',
        'add_header Cross-Origin-Resource-Policy "same-origin" always;',
        'add_header Content-Security-Policy "default-src \'self\'; script-src \'self\'; style-src \'self\' \'unsafe-inline\'; img-src \'self\' data:; font-src \'self\'; frame-ancestors \'none\'; base-uri \'self\'; form-action \'self\'" always;',
        'add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;',
    ],
    "standard": [
        'add_header X-Frame-Options "SAMEORIGIN" always;',
        'add_header X-XSS-Protection "1; mode=block" always;',
        'add_header X-Content-Type-Options "nosniff" always;',
        'add_header Referrer-Policy "no-referrer-when-downgrade" always;',
        'add_header Permissions-Policy "camera=(), microphone=()" always;',
        'add_header Content-Security-Policy "default-src \'self\' http: https: data: blob: \'unsafe-inline\'" always;',
        'add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;',
    ],
    "relaxed": [
        'add_header X-Frame-Options "SAMEORIGIN" always;',
        'add_header X-Content-Type-Options "nosniff" always;',
        'add_header Referrer-Policy "no-referrer-when-downgrade" always;',
        'add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;',
    ]
}


def build_rate_limit_directives(domain: str, preset_name: str) -> Tuple[str, str]:
    """Generates rate limit zone and location enforcement block."""
    if preset_name == "off" or preset_name not in RATE_LIMIT_PRESETS:
        return "", ""

    cfg = RATE_LIMIT_PRESETS[preset_name]
    zone_name = f"limit_{domain.replace('.', '_').replace('-', '_')}"
    zone_def = f"limit_req_zone $binary_remote_addr zone={zone_name}:{cfg['zone_size']} rate={cfg['rate']};"
    loc_directive = (
        f"    # Rate Limiting ({preset_name.capitalize()} Preset: {cfg['rate']}, burst={cfg['burst']})\n"
        f"    limit_req zone={zone_name} burst={cfg['burst']} nodelay;\n"
        f"    limit_req_status 429;"
    )
    return zone_def, loc_directive


def generate_nginx_config(
    domain: str,
    port: int,
    rate_limit_preset: str = "standard",
    security_preset: str = "strict",
    client_max_body_size: str = "50m",
    enable_websocket: bool = True
) -> str:
    """Generates production-grade hardened Nginx virtual host configuration string."""
    headers_list = SECURITY_HEADER_PRESETS.get(security_preset, SECURITY_HEADER_PRESETS["strict"])
    headers_block = "\n    ".join(headers_list)

    zone_def, loc_limit = build_rate_limit_directives(domain, rate_limit_preset)

    ws_block = ""
    if enable_websocket:
        ws_block = (
            "        # WebSocket Reverse Proxy Support\n"
            "        proxy_http_version 1.1;\n"
            "        proxy_set_header Upgrade $http_upgrade;\n"
            "        proxy_set_header Connection \"upgrade\";\n"
        )

    rate_limit_section = f"\n# Rate Limit Zone Allocation\n{zone_def}\n" if zone_def else ""

    config = f"""# ==============================================================================
# Hardened Nginx Virtual Host for: {domain}
# Generated by Nginx Security Hardener (Author: Eng. MHD. Shadi AL-Hasan)
# Security Preset: {security_preset} | Rate Limit Preset: {rate_limit_preset}
# ==============================================================================
{rate_limit_section}
server {{
    listen 80;
    listen [::]:80;
    server_name {domain};
    return 301 https://$host$request_uri;
}}

server {{
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name {domain};

    # SSL Certificates
    ssl_certificate /etc/letsencrypt/live/{domain}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/{domain}/privkey.pem;

    # Mozilla Modern SSL Configuration
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 1d;

    # Security Headers
    {headers_block}

    # Hide Nginx Version
    server_tokens off;

    # Rate Limiting & Buffer Overflow Protection
    client_body_buffer_size 16k;
    client_header_buffer_size 1k;
    client_max_body_size {client_max_body_size};
    large_client_header_buffers 4 8k;

    location / {{
{f'{loc_limit}\n' if loc_limit else ''}        proxy_pass http://127.0.0.1:{port};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
{ws_block}    }}
}}
"""
    return config


def validate_nginx_syntax_heuristics(config: str) -> Tuple[bool, List[str]]:
    """Analyzes generated config text for balanced braces and required directives."""
    errors = []
    open_braces = config.count("{")
    close_braces = config.count("}")
    if open_braces != close_braces:
        errors.append(f"Mismatched braces: {open_braces} open vs {close_braces} close.")

    required_keywords = [
        "server_name",
        "listen 80",
        "listen 443 ssl",
        "ssl_certificate",
        "proxy_pass",
        "server_tokens off",
        "Strict-Transport-Security"
    ]
    for kw in required_keywords:
        if kw not in config:
            errors.append(f"Missing required security directive: '{kw}'")

    return len(errors) == 0, errors


def generate_vhost(
    domain: str,
    port: int,
    output_file: Path,
    rate_limit_preset: str = "standard",
    security_preset: str = "strict",
    client_max_body_size: str = "50m",
    enable_websocket: bool = True
):
    content = generate_nginx_config(
        domain=domain,
        port=port,
        rate_limit_preset=rate_limit_preset,
        security_preset=security_preset,
        client_max_body_size=client_max_body_size,
        enable_websocket=enable_websocket
    )

    valid, errs = validate_nginx_syntax_heuristics(content)
    if not valid:
        raise ValueError(f"Generated configuration failed syntax checks: {', '.join(errs)}")

    output_file.write_text(content, encoding="utf-8")
    print(f"[+] Hardened Nginx configuration successfully generated at: {output_file}")


def main():
    parser = argparse.ArgumentParser(description="Generate production hardened Nginx configuration.")
    parser.add_argument("--domain", "-d", required=True, help="Domain name")
    parser.add_argument("--port", "-p", type=int, default=3000, help="Upstream application port")
    parser.add_argument("--out", "-o", default=None, help="Output config file path")
    parser.add_argument("--rate-limit", choices=["strict", "standard", "relaxed", "off"], default="standard", help="Rate limiting preset")
    parser.add_argument("--security-preset", choices=["strict", "standard", "relaxed"], default="strict", help="Security headers preset")
    parser.add_argument("--max-body", default="50m", help="Client max body size (e.g. 10m, 50m)")
    parser.add_argument("--no-websocket", action="store_true", help="Disable WebSocket proxy directives")
    args = parser.parse_args()

    out_file = Path(args.out) if args.out else Path(f"{args.domain}.conf")
    generate_vhost(
        domain=args.domain,
        port=args.port,
        output_file=out_file,
        rate_limit_preset=args.rate_limit,
        security_preset=args.security_preset,
        client_max_body_size=args.max_body,
        enable_websocket=not args.no_websocket
    )


if __name__ == "__main__":
    main()
