# -*- coding: utf-8 -*-
"""
Automated Nginx Security Hardener & VHost Config Generator
Author: Eng. MHD. Shadi AL-Hasan <mhd.shadi.alhasan@gmail.com>
Phone: +963934005922
Copyright (c) 2026 MHD. Shadi AL-Hasan
"""

import argparse
from pathlib import Path

NGINX_TEMPLATE = """# ==============================================================================
# Hardened Nginx Virtual Host for: {domain}
# Generated by Nginx Security Hardener (Author: Eng. MHD. Shadi AL-Hasan)
# ==============================================================================

server {
    listen 80;
    listen [::]:80;
    server_name {domain};
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name {domain};

    # SSL Certificates
    ssl_certificate /etc/letsencrypt/live/{domain}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/{domain}/privkey.pem;

    # Mozilla Modern SSL Configuration
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 1d;

    # Security Headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "no-referrer-when-downgrade" always;
    add_header Content-Security-Policy "default-src 'self' http: https: data: blob: 'unsafe-inline'" always;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;

    # Hide Nginx Version
    server_tokens off;

    # Rate Limiting & Buffer Overflow Protection
    client_body_buffer_size 16k;
    client_header_buffer_size 1k;
    client_max_body_size 50m;
    large_client_header_buffers 4 8k;

    location / {
        proxy_pass http://127.0.0.1:{upstream_port};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
"""

def generate_vhost(domain: str, port: int, output_file: Path):
    content = NGINX_TEMPLATE.format(domain=domain, upstream_port=port)
    output_file.write_text(content, encoding="utf-8")
    print(f"[+] Hardened Nginx configuration successfully generated at: {output_file}")

def main():
    parser = argparse.ArgumentParser(description="Generate production hardened Nginx configuration.")
    parser.add_argument("--domain", "-d", required=True, help="Domain name")
    parser.add_argument("--port", "-p", type=int, default=3000, help="Upstream application port")
    parser.add_argument("--out", "-o", default=None, help="Output config file path")
    args = parser.parse_args()

    out_file = Path(args.out) if args.out else Path(f"{args.domain}.conf")
    generate_vhost(args.domain, args.port, out_file)

if __name__ == "__main__":
    main()
